### ISSUE TITLE
make the livereload host configurable

### ISSUE THREAD

**Issue by vivmaha** [gruntjs/grunt-contrib-connect#198]
Currently, 0.0.0.0 is used as the livereload host.

I'm using grunt-contrib-watch, which uses "localhost" instead of "0.0.0.0" for livereload.

I'd like to get grunt-contrib-connect to use "localhost" so that it will be compatible with grunt-contrib-watch.

**Comment by jacksodj** [comment]
yes, for this to work on a windows machine, this is critical.

**Comment by jacksonrayhamilton** [comment]
Changes to the `connect-livereload` package [have moved hostname detection to the server](https://github.com/intesso/connect-livereload/pull/59/files), but this package [still provides](https://github.com/gruntjs/grunt-contrib-connect/blob/16f706cc67ba2e198f71d24c1549b4c5282829bd/tasks/connect.js#L144) `{hostname: options.hostname}` as an argument to the `connect-livereload` middleware, which causes the hostname to always be `0.0.0.0`. How about removing that property and letting `connect-livereload` figure out the hostname itself?

Is [the issue that prompted that change](https://github.com/gruntjs/grunt-contrib-connect/pull/134) still applicable? Should we have a different name for the livereload hostname configuration option?

Rather than specifying `{livereload: true}` for this plugin's configuration, as a workaround you can add the middleware yourself and you should get the dynamic behavior:

```js
options: {
  middleware: function (connect, options, middlewares) {
    middlewares.unshift(
      require('connect-livereload')()
    );
    return middlewares;
  }
}
```

**Comment by vmaha** [comment]
I am now able to solve this by adding setting the `hostname` option to `localhost`.

```
        connect: {
            server: {
                options: {
                    port: 9001,
                    base: './build',                    
                    livereload: true,
**                    hostname:'localhost',**
                },
            },
        },
```

**Comment by Jorjon** [comment]
If you want to work with anoter device, in `hostname` you should specify the network address (e.g. 192.168.0.101).
