### ISSUE TITLE
40kb limit on html files

### ISSUE THREAD

**Issue by daspecster** [gruntjs/grunt-contrib-connect#20]
When using `grunt server`, files with the text/html mimetype only load the first 40960 bytes.

Not sure if this is something that can be changed via connect.limit()? I tried to change it with that but I failed miserably.

To reproduce, make an html file larger than 40kb and curl it or view it in your browser.

I tried setting this up with just senchalabs connect() and it served the whole file so I assume it's something with grunt or this plugin.

Example: 
https://github.com/daspecster/grunt-server-limit-example

**Comment by kevin-smets** [comment]
This is still an issue for us, has this been looked into further?

**Comment by haxaco** [comment]
Same here, our pages are being cut and we're working with grunt contrib watch (0.6.1) and connect (0.9.0). Should we roll back to 0.6.0?

**Comment by andineck** [comment]
It once was an issue with `connect-livereload`, but it should have been fixed... I quickly checked the versions: `grunt-contrib-connect` 0.9.0 uses `connect-livereload` 0.5.0 (the latest one would be 0.5.0), but this bug was supposed to be fixed in 0.5.0 already. 
https://github.com/intesso/connect-livereload/compare/v0.5.0...v0.5.2

there is a test with large files (~2.9MB):
https://github.com/intesso/connect-livereload/blob/master/test/app.render.large-file.js

anyway, can you send me a test file or add a test case to connect-livereload?

**Comment by andineck** [comment]
I just updated `connect-livereload`'s test dependencies and added another test case with connect and large files. v0.5.3.

The tests run with:
    "connect": "^3.3.4",
    "express": "~4.11.2",

**Comment by andineck** [comment]
do you use some other middleware with size limits? e.g.:
https://github.com/expressjs/body-parser#limit
